services:
  db:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  product:
    build: ./api/product
    command: npm run dev
    restart: always
    env_file: ./api/product/.env
    volumes:
      - ./api/product/src:/app/src
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  uploadimage:
    build: ./api/uploadimage
    command: npm run dev
    restart: always
    env_file: ./api/uploadimage/.env
    environment:
      - VITE_API_URL=http://localhost:5050/upload
    volumes:
      - ./api/uploadimage/src:/app/src
      - ./api/uploadimage/uploads:/app/uploads
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  auth:
    build: ./api/auth
    command: npm run dev
    restart: always
    env_file: ./api/auth/.env
    volumes:
      - ./api/auth/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  email:
    build: ./api/email
    command: npm run dev
    restart: always
    env_file: ./api/email/.env
    volumes:
      - ./api/email/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  client:
    build: ./client
    command: npm run dev
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5050/graph
    volumes:
      - ./client/src:/app/src
    networks:
      - mynetwork

  gateway:
    image: nginx
    ports:
      - 5050:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product
      - uploadimage
      - auth
      - email
      - client
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
